### ISSUE TITLE
Add-on does not stream image to the app when using Metal backend.

### ISSUE THREAD

**Issue by satishgoda** [shycats/VirtuCameraBlender#17]
Blender 3.5 introduces the Metal backend on MacOS platform and when using VirtuCamera on those devices, the streaming of the viewport does not occur. It says that the gpu module must be used, instead of the bgl module.

**Comment by marianlandrieve** [comment]
This is the blender error repport if that can help :
One of the add-ons or scripts is using OpenGL and will not work correct on Metal. Please contact the developer of the add-on to migrate to use 'gpu' module

**Comment by sgodanas** [comment]
Here is a more detailed error as well.

```
Device with name Apple M1 Pro supports metal minimum requirements
METAL API - DETECTED GPU: Apple M1 Pro
WARN (bgl): source/blender/python/generic/bgl.c:2662 BPyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module. In Blender 4.0 'bgl' will be removed.
```

**Comment by shycats** [comment]
Hello @satishgoda, @marianlandrieve, @sgodanas, I've just update the plug-in to support the new gpu Blender API, it should work now on latest Blender versions and M1 Macs, please let me know if you find any issues, thanks!
Release:
https://github.com/shycats/VirtuCameraBlender/releases/tag/v1.2.0_3.4

**Comment by sgodanas** [comment]
Hi @shycats 

It is working fine with 3.6! Although the plugin version in the addon display in Blender still shows as 1.1.1.

Thank you for making the changes!

Satish.
